dependent_variable:
    Attrition_Flag

numerical_variables:
    - Customer_Age
    - Dependent_count
    - Months_on_book
    - Total_Relationship_Count
    - Months_Inactive_12_mon
    - Contacts_Count_12_mon
    - Credit_Limit
    - Total_Revolving_Bal
    - Avg_Open_To_Buy
    - Total_Amt_Chng_Q4_Q1
    - Total_Trans_Amt
    - Total_Trans_Ct
    - Total_Ct_Chng_Q4_Q1
    - Avg_Utilization_Ratio

categorical_variables:
    - Gender
    - Education_Level
    - Marital_Status
    - Income_Category
    - Card_Category

remove_variables:
    - CLIENTNUM
    - Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1
    - Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2

# Outlier Analysis
z_score_boundaries:
    Credit_Limit:
        - -18634.376252634494
        - 35898.283648704186
    Total_Amt_Chng_Q4_Q1:
        - 0.10232034600593021
        - 1.4175609613901452
    Total_Ct_Chng_Q4_Q1:
        - -0.0020358981718290314
        - 1.4264806498258213

# Variable Transformation
numerical_variables_YJ:
    - Credit_Limit
    - Total_Revolving_Bal
    - Avg_Open_To_Buy
    - Avg_Utilization_Ratio

# Mapping Variables
mapping_variables:
    Education_Level:
        Unknown: 0
        Uneducated: 1
        High School: 2
        College: 3
        Graduate: 4
        Post-Graduate: 5
        Doctorate: 6

    Income_Category:
        Unknown: 0
        Less than $40K: 1
        $40K - $60K: 2
        $60K - $80K: 3
        $80K - $120K: 4
        $120K +: 5

    Card_Category:
        Blue: 0
        Silver: 1
        Gold: 1
        Platinum: 1

    Gender:
        M: 0
        F: 1

    Attrition_Flag:
        Existing Customer: 0
        Attrited Customer: 1

# Dummy Variables
dummy_variables:
    - Marital_Status

# Highly Correlated Numerical Variables
correlated_variables:
    - Months_on_book
    - Avg_Open_To_Buy
    - Total_Trans_Ct

# Most important variables so far
important_variables:
    - Total_Relationship_Count 
    - Total_Revolving_Bal 
    - Total_Amt_Chng_Q4_Q1 
    - Total_Trans_Amt 
    - Total_Ct_Chng_Q4_Q1 
    - Avg_Utilization_Ratio 

non_significant_variables:
    - Customer_Age
    - Total_Amt_Chng_Q4_Q1
    - Education_Level 

